/********************************************************************************
** Form generated from reading UI file 'my3dviewer.ui'
**
** Created: Thu Apr 26 19:43:50 2012
**      by: Qt User Interface Compiler version 4.8.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MY3DVIEWER_H
#define UI_MY3DVIEWER_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QComboBox>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QMainWindow>
#include <QtGui/QSlider>
#include <QtGui/QSpinBox>
#include <QtGui/QWidget>
#include "myglwidget.h"

QT_BEGIN_NAMESPACE

class Ui_My3DViewerClass
{
public:
    QWidget *centralWidget;
    QLabel *label_7;
    QLabel *label_6;
    QSpinBox *spinBox_8;
    QSpinBox *spinBox_10;
    QSpinBox *spinBox_9;
    QLabel *label_8;
    QLabel *label_12;
    QLabel *label_10;
    QSpinBox *spinBox_12;
    QLabel *label_9;
    QSpinBox *spinBox_13;
    QLabel *label_5;
    QLabel *label_11;
    QSpinBox *spinBox_11;
    QLabel *label_4;
    QComboBox *selectionModes;
    MyGLWidget *mainWindowClass;
    QLabel *label;
    QFrame *frame;
    QLabel *label_3;
    QSpinBox *spinBox;
    QSpinBox *spinBox_7;
    QLabel *label_14;
    QSpinBox *spinBox_5;
    QSpinBox *spinBox_4;
    QSpinBox *spinBox_2;
    QLabel *label_13;
    QSpinBox *spinBox_3;
    QLabel *label_20;
    QLabel *label_21;
    QFrame *frame_2;
    QLabel *label_16;
    QLabel *label_15;
    QSlider *blueVal;
    QSlider *greenVal;
    QSlider *redVal;
    QLabel *label_2;
    QSlider *twistX;
    QSlider *twistY;
    QSlider *twistZ;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_22;

    void setupUi(QMainWindow *My3DViewerClass)
    {
        if (My3DViewerClass->objectName().isEmpty())
            My3DViewerClass->setObjectName(QString::fromUtf8("My3DViewerClass"));
        My3DViewerClass->resize(1051, 718);
        QPalette palette;
        QBrush brush(QColor(239, 239, 239, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(255, 255, 255, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        QBrush brush2(QColor(84, 84, 84, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush2);
        QBrush brush3(QColor(120, 120, 120, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush2);
        My3DViewerClass->setPalette(palette);
        My3DViewerClass->setAutoFillBackground(false);
        My3DViewerClass->setStyleSheet(QString::fromUtf8("background-image: url(:/StarterCode/background.png);"));
        centralWidget = new QWidget(My3DViewerClass);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        QPalette palette1;
        QBrush brush4(QColor(247, 143, 68, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        QBrush brush5(QColor(62, 62, 62, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush5);
        QBrush brush6(QColor(236, 236, 236, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        centralWidget->setPalette(palette1);
        centralWidget->setAutoFillBackground(false);
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(760, 550, 16, 16));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        label_7->setFont(font);
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(700, 550, 16, 16));
        label_6->setFont(font);
        spinBox_8 = new QSpinBox(centralWidget);
        spinBox_8->setObjectName(QString::fromUtf8("spinBox_8"));
        spinBox_8->setGeometry(QRect(720, 550, 31, 20));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        QBrush brush7(QColor(0, 0, 0, 255));
        brush7.setStyle(Qt::NoBrush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        QBrush brush8(QColor(0, 0, 0, 255));
        brush8.setStyle(Qt::NoBrush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        QBrush brush9(QColor(0, 0, 0, 255));
        brush9.setStyle(Qt::NoBrush);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        spinBox_8->setPalette(palette2);
        spinBox_8->setStyleSheet(QString::fromUtf8("color: #FFFFFF"));
        spinBox_8->setMinimum(1);
        spinBox_8->setMaximum(5);
        spinBox_10 = new QSpinBox(centralWidget);
        spinBox_10->setObjectName(QString::fromUtf8("spinBox_10"));
        spinBox_10->setGeometry(QRect(780, 550, 31, 20));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        QBrush brush10(QColor(0, 0, 0, 255));
        brush10.setStyle(Qt::NoBrush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        QBrush brush11(QColor(0, 0, 0, 255));
        brush11.setStyle(Qt::NoBrush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush11);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        QBrush brush12(QColor(0, 0, 0, 255));
        brush12.setStyle(Qt::NoBrush);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush12);
        spinBox_10->setPalette(palette3);
        spinBox_10->setStyleSheet(QString::fromUtf8("color: #FFFFFF"));
        spinBox_10->setMinimum(1);
        spinBox_10->setMaximum(5);
        spinBox_9 = new QSpinBox(centralWidget);
        spinBox_9->setObjectName(QString::fromUtf8("spinBox_9"));
        spinBox_9->setGeometry(QRect(840, 550, 31, 20));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        QBrush brush13(QColor(0, 0, 0, 255));
        brush13.setStyle(Qt::NoBrush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        QBrush brush14(QColor(0, 0, 0, 255));
        brush14.setStyle(Qt::NoBrush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush14);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        QBrush brush15(QColor(0, 0, 0, 255));
        brush15.setStyle(Qt::NoBrush);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush15);
        spinBox_9->setPalette(palette4);
        spinBox_9->setStyleSheet(QString::fromUtf8("color: #FFFFFF"));
        spinBox_9->setMinimum(1);
        spinBox_9->setMaximum(5);
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(820, 550, 16, 16));
        label_8->setFont(font);
        label_12 = new QLabel(centralWidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(700, 610, 16, 16));
        label_12->setFont(font);
        label_10 = new QLabel(centralWidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(760, 610, 16, 16));
        label_10->setFont(font);
        spinBox_12 = new QSpinBox(centralWidget);
        spinBox_12->setObjectName(QString::fromUtf8("spinBox_12"));
        spinBox_12->setGeometry(QRect(780, 610, 31, 20));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        QBrush brush16(QColor(0, 0, 0, 255));
        brush16.setStyle(Qt::NoBrush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush16);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        QBrush brush17(QColor(0, 0, 0, 255));
        brush17.setStyle(Qt::NoBrush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush17);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        QBrush brush18(QColor(0, 0, 0, 255));
        brush18.setStyle(Qt::NoBrush);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush18);
        spinBox_12->setPalette(palette5);
        spinBox_12->setStyleSheet(QString::fromUtf8("color: #FFFFFF"));
        spinBox_12->setMinimum(0);
        spinBox_12->setMaximum(5);
        spinBox_12->setValue(0);
        label_9 = new QLabel(centralWidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(820, 610, 16, 16));
        label_9->setFont(font);
        spinBox_13 = new QSpinBox(centralWidget);
        spinBox_13->setObjectName(QString::fromUtf8("spinBox_13"));
        spinBox_13->setGeometry(QRect(840, 610, 31, 20));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        QBrush brush19(QColor(0, 0, 0, 255));
        brush19.setStyle(Qt::NoBrush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush19);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        QBrush brush20(QColor(0, 0, 0, 255));
        brush20.setStyle(Qt::NoBrush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush20);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        QBrush brush21(QColor(0, 0, 0, 255));
        brush21.setStyle(Qt::NoBrush);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush21);
        spinBox_13->setPalette(palette6);
        spinBox_13->setStyleSheet(QString::fromUtf8("color: #FFFFFF"));
        spinBox_13->setMinimum(0);
        spinBox_13->setMaximum(5);
        spinBox_13->setValue(0);
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(698, 591, 94, 16));
        label_11 = new QLabel(centralWidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(700, 530, 139, 16));
        spinBox_11 = new QSpinBox(centralWidget);
        spinBox_11->setObjectName(QString::fromUtf8("spinBox_11"));
        spinBox_11->setGeometry(QRect(720, 610, 27, 20));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        QBrush brush22(QColor(0, 0, 0, 255));
        brush22.setStyle(Qt::NoBrush);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush22);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        QBrush brush23(QColor(0, 0, 0, 255));
        brush23.setStyle(Qt::NoBrush);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush23);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        QBrush brush24(QColor(0, 0, 0, 255));
        brush24.setStyle(Qt::NoBrush);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush24);
        spinBox_11->setPalette(palette7);
        spinBox_11->setStyleSheet(QString::fromUtf8("color: #FFFFFF"));
        spinBox_11->setMinimum(0);
        spinBox_11->setMaximum(5);
        spinBox_11->setValue(0);
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(290, 680, 41, 21));
        label_4->setFont(font);
        selectionModes = new QComboBox(centralWidget);
        selectionModes->setObjectName(QString::fromUtf8("selectionModes"));
        selectionModes->setGeometry(QRect(340, 680, 170, 20));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        QBrush brush25(QColor(0, 0, 0, 255));
        brush25.setStyle(Qt::SolidPattern);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush25);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush25);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush25);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush25);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        selectionModes->setPalette(palette8);
        selectionModes->setStyleSheet(QString::fromUtf8(""));
        mainWindowClass = new MyGLWidget(centralWidget);
        mainWindowClass->setObjectName(QString::fromUtf8("mainWindowClass"));
        mainWindowClass->setGeometry(QRect(90, 60, 600, 600));
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(mainWindowClass->sizePolicy().hasHeightForWidth());
        mainWindowClass->setSizePolicy(sizePolicy);
        label = new QLabel(centralWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(820, 240, 81, 21));
        frame = new QFrame(centralWidget);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(700, 100, 311, 111));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        frame->setLineWidth(1);
        frame->setMidLineWidth(0);
        label_3 = new QLabel(frame);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(170, 30, 16, 16));
        spinBox = new QSpinBox(frame);
        spinBox->setObjectName(QString::fromUtf8("spinBox"));
        spinBox->setGeometry(QRect(160, 80, 33, 20));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        QBrush brush26(QColor(0, 0, 0, 255));
        brush26.setStyle(Qt::NoBrush);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush26);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        QBrush brush27(QColor(0, 0, 0, 255));
        brush27.setStyle(Qt::NoBrush);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush27);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        QBrush brush28(QColor(0, 0, 0, 255));
        brush28.setStyle(Qt::NoBrush);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush28);
        spinBox->setPalette(palette9);
        spinBox->setStyleSheet(QString::fromUtf8("color: #FFFFFF"));
        spinBox->setMinimum(-99);
        spinBox_7 = new QSpinBox(frame);
        spinBox_7->setObjectName(QString::fromUtf8("spinBox_7"));
        spinBox_7->setGeometry(QRect(208, 53, 33, 20));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        QBrush brush29(QColor(0, 0, 0, 255));
        brush29.setStyle(Qt::NoBrush);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush29);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        QBrush brush30(QColor(0, 0, 0, 255));
        brush30.setStyle(Qt::NoBrush);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush30);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        QBrush brush31(QColor(0, 0, 0, 255));
        brush31.setStyle(Qt::NoBrush);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush31);
        spinBox_7->setPalette(palette10);
        spinBox_7->setStyleSheet(QString::fromUtf8("color: #FFFFFF"));
        spinBox_7->setMinimum(-99);
        label_14 = new QLabel(frame);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(15, 80, 131, 20));
        spinBox_5 = new QSpinBox(frame);
        spinBox_5->setObjectName(QString::fromUtf8("spinBox_5"));
        spinBox_5->setGeometry(QRect(160, 53, 33, 20));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        QBrush brush32(QColor(0, 0, 0, 255));
        brush32.setStyle(Qt::NoBrush);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush32);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        QBrush brush33(QColor(0, 0, 0, 255));
        brush33.setStyle(Qt::NoBrush);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush33);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        QBrush brush34(QColor(0, 0, 0, 255));
        brush34.setStyle(Qt::NoBrush);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush34);
        spinBox_5->setPalette(palette11);
        spinBox_5->setStyleSheet(QString::fromUtf8("color: #FFFFFF"));
        spinBox_5->setMinimum(-99);
        spinBox_4 = new QSpinBox(frame);
        spinBox_4->setObjectName(QString::fromUtf8("spinBox_4"));
        spinBox_4->setGeometry(QRect(258, 53, 33, 20));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        QBrush brush35(QColor(0, 0, 0, 255));
        brush35.setStyle(Qt::NoBrush);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush35);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        QBrush brush36(QColor(0, 0, 0, 255));
        brush36.setStyle(Qt::NoBrush);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush36);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        QBrush brush37(QColor(0, 0, 0, 255));
        brush37.setStyle(Qt::NoBrush);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush37);
        spinBox_4->setPalette(palette12);
        spinBox_4->setStyleSheet(QString::fromUtf8("color: #FFFFFF"));
        spinBox_4->setMinimum(-99);
        spinBox_2 = new QSpinBox(frame);
        spinBox_2->setObjectName(QString::fromUtf8("spinBox_2"));
        spinBox_2->setGeometry(QRect(208, 80, 33, 20));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        QBrush brush38(QColor(0, 0, 0, 255));
        brush38.setStyle(Qt::NoBrush);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush38);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        QBrush brush39(QColor(0, 0, 0, 255));
        brush39.setStyle(Qt::NoBrush);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush39);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        QBrush brush40(QColor(0, 0, 0, 255));
        brush40.setStyle(Qt::NoBrush);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush40);
        spinBox_2->setPalette(palette13);
        spinBox_2->setStyleSheet(QString::fromUtf8("color: #FFFFFF"));
        spinBox_2->setMinimum(-99);
        label_13 = new QLabel(frame);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(17, 50, 121, 21));
        spinBox_3 = new QSpinBox(frame);
        spinBox_3->setObjectName(QString::fromUtf8("spinBox_3"));
        spinBox_3->setGeometry(QRect(258, 80, 33, 20));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette14.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        QBrush brush41(QColor(0, 0, 0, 255));
        brush41.setStyle(Qt::NoBrush);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush41);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        QBrush brush42(QColor(0, 0, 0, 255));
        brush42.setStyle(Qt::NoBrush);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush42);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        QBrush brush43(QColor(0, 0, 0, 255));
        brush43.setStyle(Qt::NoBrush);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush43);
        spinBox_3->setPalette(palette14);
        spinBox_3->setStyleSheet(QString::fromUtf8("color: #FFFFFF"));
        spinBox_3->setMinimum(-99);
        label_20 = new QLabel(frame);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(220, 30, 16, 16));
        label_21 = new QLabel(frame);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(270, 30, 16, 16));
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(750, 270, 221, 211));
        frame_2->setStyleSheet(QString::fromUtf8("opacity: 0.2"));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        label_16 = new QLabel(frame_2);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(90, 180, 41, 16));
        label_15 = new QLabel(frame_2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(170, 180, 21, 16));
        blueVal = new QSlider(frame_2);
        blueVal->setObjectName(QString::fromUtf8("blueVal"));
        blueVal->setGeometry(QRect(170, 20, 19, 160));
        blueVal->setMaximum(255);
        blueVal->setOrientation(Qt::Vertical);
        greenVal = new QSlider(frame_2);
        greenVal->setObjectName(QString::fromUtf8("greenVal"));
        greenVal->setGeometry(QRect(100, 20, 19, 160));
        greenVal->setMaximum(255);
        greenVal->setOrientation(Qt::Vertical);
        redVal = new QSlider(frame_2);
        redVal->setObjectName(QString::fromUtf8("redVal"));
        redVal->setGeometry(QRect(30, 20, 19, 160));
        redVal->setMaximum(255);
        redVal->setOrientation(Qt::Vertical);
        label_2 = new QLabel(frame_2);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(30, 180, 31, 16));
        twistX = new QSlider(centralWidget);
        twistX->setObjectName(QString::fromUtf8("twistX"));
        twistX->setGeometry(QRect(910, 530, 20, 121));
        twistX->setOrientation(Qt::Vertical);
        twistY = new QSlider(centralWidget);
        twistY->setObjectName(QString::fromUtf8("twistY"));
        twistY->setGeometry(QRect(960, 530, 20, 121));
        twistY->setOrientation(Qt::Vertical);
        twistZ = new QSlider(centralWidget);
        twistZ->setObjectName(QString::fromUtf8("twistZ"));
        twistZ->setGeometry(QRect(1010, 530, 20, 121));
        twistZ->setOrientation(Qt::Vertical);
        label_17 = new QLabel(centralWidget);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(930, 500, 81, 20));
        label_18 = new QLabel(centralWidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(910, 660, 16, 16));
        label_19 = new QLabel(centralWidget);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(960, 660, 16, 16));
        label_22 = new QLabel(centralWidget);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(1010, 660, 16, 16));
        My3DViewerClass->setCentralWidget(centralWidget);

        retranslateUi(My3DViewerClass);
        QObject::connect(spinBox, SIGNAL(valueChanged(int)), mainWindowClass, SLOT(setrefx(int)));
        QObject::connect(spinBox_2, SIGNAL(valueChanged(int)), mainWindowClass, SLOT(setrefy(int)));
        QObject::connect(spinBox_3, SIGNAL(valueChanged(int)), mainWindowClass, SLOT(setrefz(int)));
        QObject::connect(selectionModes, SIGNAL(activated(int)), mainWindowClass, SLOT(setselectionmode(int)));
        QObject::connect(spinBox_4, SIGNAL(valueChanged(int)), mainWindowClass, SLOT(setlightz(int)));
        QObject::connect(spinBox_5, SIGNAL(valueChanged(int)), mainWindowClass, SLOT(setlighty(int)));
        QObject::connect(spinBox_7, SIGNAL(valueChanged(int)), mainWindowClass, SLOT(setlightx(int)));
        QObject::connect(spinBox_8, SIGNAL(valueChanged(int)), mainWindowClass, SLOT(setdeformi(int)));
        QObject::connect(spinBox_10, SIGNAL(valueChanged(int)), mainWindowClass, SLOT(setdeformj(int)));
        QObject::connect(spinBox_9, SIGNAL(valueChanged(int)), mainWindowClass, SLOT(setdeformk(int)));
        QObject::connect(spinBox_11, SIGNAL(valueChanged(int)), mainWindowClass, SLOT(selectcontrolx(int)));
        QObject::connect(spinBox_12, SIGNAL(valueChanged(int)), mainWindowClass, SLOT(selectcontroly(int)));
        QObject::connect(spinBox_13, SIGNAL(valueChanged(int)), mainWindowClass, SLOT(selectcontrolz(int)));
        QObject::connect(mainWindowClass, SIGNAL(sendcurrentface(Face*)), My3DViewerClass, SLOT(setColorSliders(Face*)));
        QObject::connect(redVal, SIGNAL(valueChanged(int)), My3DViewerClass, SLOT(changeFaceR(int)));
        QObject::connect(greenVal, SIGNAL(valueChanged(int)), My3DViewerClass, SLOT(changeFaceG(int)));
        QObject::connect(blueVal, SIGNAL(valueChanged(int)), My3DViewerClass, SLOT(changeFaceB(int)));
        QObject::connect(twistZ, SIGNAL(valueChanged(int)), mainWindowClass, SLOT(twistZ(int)));
        QObject::connect(twistX, SIGNAL(valueChanged(int)), mainWindowClass, SLOT(twistX(int)));
        QObject::connect(twistY, SIGNAL(valueChanged(int)), mainWindowClass, SLOT(twistY(int)));

        QMetaObject::connectSlotsByName(My3DViewerClass);
    } // setupUi

    void retranslateUi(QMainWindow *My3DViewerClass)
    {
        My3DViewerClass->setWindowTitle(QApplication::translate("My3DViewerClass", "My 3D Viewer", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p><span style=\" color:#ffffff;\">j</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p><span style=\" color:#ffffff;\">i</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p><span style=\" color:#ffffff;\">k</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p><span style=\" color:#ffffff;\">x</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p><span style=\" color:#ffffff;\">y</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p><span style=\" color:#ffffff;\">z</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p><span style=\" color:#ffffff;\">Select Control Point</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p><span style=\" color:#ffffff;\">Set Number of Control Points</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p><span style=\" color:#ffffff;\">Mode :</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        selectionModes->clear();
        selectionModes->insertItems(0, QStringList()
         << QApplication::translate("My3DViewerClass", "Face Selection", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("My3DViewerClass", "Edge Selection", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("My3DViewerClass", "Vertex Selection", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("My3DViewerClass", "Free-Form Deformation", 0, QApplication::UnicodeUTF8)
        );
        label->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">Face Color</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p><span style=\" color:#ffffff;\">x</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p><span style=\" color:#ffffff;\">Camera Reference Point</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p><span style=\" color:#ffffff;\">Set Light Source</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p><span style=\" color:#ffffff;\">y</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p><span style=\" color:#ffffff;\">z</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Green</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p><span style=\" color:#ffffff;\">Blue</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p><span style=\" color:#ffffff;\">Red</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Twist Controls</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">x</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">y</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("My3DViewerClass", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">z</span></p></body></html>", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class My3DViewerClass: public Ui_My3DViewerClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MY3DVIEWER_H
